# https://github.com/jetplugins/apidocx/blob/main/docs/GUIDE.md
yapiProjectId=
rap2ProjectId=
eolinkerProjectId=
showdocProjectId=
returnWrapType=

# Copy Api as Markdown for LLMs (optional)
# llmServiceEndpoint=http://smart-assistant
# llmMavenDependency=<dependency>...</dependency>

